[build-system]
requires = ["setuptools", "wheel", "cython", "numpy", "torch==2.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "mask2former"
version = "0.6" # Adotta la versione di Detectron2
dependencies = [
    # Aggiungi qui le dipendenze essenziali se non fossero già in requirements.txt
]

[tool.setuptools.packages.find]
where = ["."] # Cerca i pacchetti nella cartella corrente
include = ["mask2former*"] # Include tutti i moduli che iniziano per mask2former